# Generated by Django 4.0.5 on 2022-06-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapi', '0003_alter_book_isbn_alter_bookreview_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='total',
        ),
    ]
