# Generated by Django 4.0.5 on 2022-07-05 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapi', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
