# Generated by Django 4.0.5 on 2022-07-05 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapi', '0005_remove_cart_products_alter_cart_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_item',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ecommapi.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
