# Generated by Django 4.0.5 on 2022-06-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapi', '0005_alter_cart_cart_id_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['user_id', '-created_on']},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['user_id', '-created_on']},
        ),
    ]
