# Generated by Django 4.0.5 on 2022-07-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapi', '0006_alter_order_order_number_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20),
        ),
    ]
