# Generated by Django 4.0.5 on 2022-07-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapi', '0009_alter_order_order_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
