# Generated by Django 4.0.5 on 2022-07-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapi', '0011_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
